BUILD_DIR?=../litex/build/colorlight_i5

include $(BUILD_DIR)/software/include/generated/variables.mak
include $(SOC_DIRECTORY)/software/common.mak

OBJECTS   = crt0.o main.o rfm95.o aht10.o

all: main.bin

-include $(OBJECTS:.o=.d)

%.bin: %.elf
	$(OBJCOPY) -O binary $< $@
	chmod -x $@

main.elf: $(OBJECTS)
	$(CC) $(LDFLAGS) -T linker.ld -N -o $@ \
		$(OBJECTS) \
		$(PACKAGES:%=-L$(BUILD_DIR)/software/%) \
		-Wl,--gc-sections \
		-Wl,-Map,$@.map \
		-Wl,-u,_printf_float \
		-Wl,--start-group \
		$(LIBS:lib%=-l%) \
		-lc -lm -lgcc \
		-Wl,--end-group
	chmod -x $@


crt0.o: $(CPU_DIRECTORY)/crt0.S
	$(assemble)

# ---- fontes que estão em lib/ ----
rfm95.o: lib/rfm95.c
	$(compile)

aht10.o: lib/aht10.c
	$(compile)

# ---- regras genéricas ----
%.o: %.c
	$(compile)

%.o: %.S
	$(assemble)

clean:
	$(RM) $(OBJECTS) main.elf main.bin .*~ *~

.PHONY: all clean
